### ISSUE TITLE
Support for CH340E

### ISSUE THREAD

**Issue by drSchaps** [senthilnathant/tools-ch340b-configuration#1]
Hi,
good work with CH340b, but I would like to ask if there is any chance to support CH340E chips.

Regards

Martin

**Comment by senthilnathant** [comment]
Hi Martin, 

As per the datasheet of CH340, it seems the CH340E doesn't have an internal E2PROM for storing this modifiable configuration data. The configuration data could have been hard coded and couldn't be modified for CH340E. But let me know if you have any other source that claims CH340E 's configuration data can be updated.

Thank You,
Senthil
